Update Chemistry-Reagents-Other.dm
rhailrake/SS13-SCP13 pull request #12
Opened 2021-04-05 18:02 UTC by hnappinn

- Усилил ролеплейную силу амнезиаков добавив перевод
- Замахнулся на амнезиак класса Д который стирает меметические аномалии (если что эти амнезиаки все же сделанны по новому лору, и их цвет тоже соответствует http://scpfoundation.net/amnestic-orientation-manual)

2021-04-05 18:18 UTC, VoiceInYourHead requested changes
Ниже привёл пару...Ну, ладно, кучу моментов, которые стоит поправить

2021-04-05 18:18 UTC, VoiceInYourHead commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
> +	to_chat(M, "<span class='notice'>Вы чувствуете, что ваша память отдаляется...")
Мне кажется лучше написать что-то вроде: "Вы ощущаете, как нечто очень важное ускользает от вас...". Конечно, так сразу хуй поймёшь, что имеется в виду, но если челик хоть немного шарит за Фонд - он поймёт

2021-04-05 18:18 UTC, VoiceInYourHead commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
> +	to_chat(M, "<span class='boldannounce'>Вы потеряли всю память до начала последнего эксперимента (если есть).  Вы должны соответственно отыгрывать.</span>")
То же самое. Перевод, конечно, правильный, но не очень приятный для прочтения. Ниже я приведу ещё правки по этому же поводу.

Тут же лучше было написать что-то вроде: "Кажется, вы забыли о всём, что происходило последние минут 10..."

Без вот этих пометок про эксперименты и ралиплей. Это ломает погружение.

2021-04-05 18:18 UTC, VoiceInYourHead commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
> +	to_chat(M, "<span class='notice'>Ваш мозг чувствует себя немного... пустым...")
"Все мысли будто бы вылетели из головы..."

2021-04-05 18:18 UTC, VoiceInYourHead commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
> +	to_chat(M, "<span class='boldannounce'>Вы потеряли всю память до точки, когда начался раунд и вы проснулись.  Вы должны соответственно отыгрывать.</span>")
"Вы ничего не можете вспомнить...Только вы находились в вагоне служебного поезда, а теперь?..."

2021-04-05 18:18 UTC, VoiceInYourHead commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
> +	to_chat(M, "<span class='notice'>Воспоминания вырваны из головы!")
"Чувство такое, будто бы кто-то вырвал все воспоминания с корнем..."

2021-04-05 18:18 UTC, VoiceInYourHead commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
> +	to_chat(M, "<span class='boldannounce'>Вы потеряли всю память до точки, когда вы прибыли в Фонд, и понятия не имеете, как вы сюда попали.  Вы должны соответственно отыгрывать.</span>")
"Кажется, единственное что вы помните - это то как подписывали какие-то бумаги в кабинете с человеком в белом медицинском халате. Как вы тут вообще оказались?"

2021-04-05 18:18 UTC, VoiceInYourHead commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
> +/datum/reagent/amnestics/classc
Если копируешь - не забывай менять пути. У тебя получается два амнезиака класса C

2021-04-05 18:18 UTC, VoiceInYourHead commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
> +	to_chat(M, "<span class='boldannounce'>Вы потеряли всю память до точки, когда вы прибыли в Фонд, а так же еще 2 две недели своей жизни, и понятия не имеете, как вы сюда попали.  Вы должны соответств
Всё то же самое, что в С, но с добавлением про последние несколько недель.

2021-04-05 18:18 UTC, VoiceInYourHead commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
> +	to_chat(M, "<span class='boldannounce'>Вы потеряли всю память, которую вы удерживаете, дорогой, и каждый аспект вашей личности был разорван, чтобы быть повторно слепленным, как глина.  Вы должны соо
"Ваша личность будто бы была стёрта и слеплена с нуля, как какая-то скульптура. Вы ничего не помните. Ни того, кем вы были в прошлом, ни того, зачем вообще подписались на всё это..."

2021-04-05 18:21 UTC, VoiceInYourHead commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
> +	to_chat(M, "<span class='boldannounce'>Вы потеряли всю память до точки, когда вы прибыли в Фонд, а так же еще 2 две недели своей жизни, и понятия не имеете, как вы сюда попали.  Вы должны соответств
В принципе, вообще, можно было бы этот текст и переписать несколько, если ты пытался сделать программируемый амнезиак для Дшек. Что-то вроде "Вы помните только то, что подписались на программу реабилитации, любезно предложенную вам Фондом"

2021-04-05 19:02 UTC, hnappinn commented
@VoiceInYourHead  Я сделал

2021-04-05 19:39 UTC, hnappinn commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
> +	to_chat(M, "<span class='boldannounce'>Вы потеряли всю память до точки, когда вы прибыли в Фонд, а так же еще 2 две недели своей жизни, и понятия не имеете, как вы сюда попали.  Вы должны соответств
Я не знаю как сделать для дешек другой текст

2021-04-05 19:47 UTC, hnappinn commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
> +	to_chat(M, "<span class='boldannounce'>Вы потеряли всю память до точки, когда вы прибыли в Фонд, а так же еще 2 две недели своей жизни, и понятия не имеете, как вы сюда попали.  Вы должны соответств
Ну по канону на который опирались создатели этих амнезиаков, это непрограммируемый

2021-04-05 19:50 UTC, hnappinn commented
Кто может, помогите пожалуйста допилить лечение эффектов колокольчика и других меметических аномалий для амнезиака класса D

2021-04-06 03:58 UTC, rhailrake commented
@VoiceInYourHead прочекай все последний раз, если все ок я мержу и дописываю лечение эффектов колокольчика

2021-04-06 05:52 UTC, rhailrake commented
![image](https://user-images.githubusercontent.com/49613070/113665031-9c05fe80-96ce-11eb-860a-d9d8144064ee.png)

2021-04-06 05:53 UTC, merged